# Задача регрессии

In [27]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn import linear_model
from geopy.distance import vincenty
import matplotlib.pyplot as plt
import plotly.graph_objs as go
import seaborn as sns

## Первичный анализ данных и подготовка данных
### Интеграция данных

In [28]:
df_vacancy = pd.read_csv('hh_vacancy.csv')
df_vacancy

,id,area_id,area_name,employer_id,employment_id,employment_name,experience_id,experience_name,key_skills,name,published_at,salary_currency,salary_from,salary_to,schedule_id,schedule_name,specialization_id,specialization_name
0,25607531,1,Москва,1747017.0,full,Полная занятость,between3And6,От 3 до 6 лет,"PHP, Symfony, PostgreSQL, Redis, Design Patter...",Senior/Middle PHP-Developer,2018-05-06T17:43:45+0300,RUR,120000.0,170000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
1,25435136,1,Москва,553714.0,project,Проектная работа,between3And6,От 3 до 6 лет,NaN,Ведущий фронтенд-разработчик,2018-05-05T14:43:01+0300,NaN,NaN,NaN,remote,Удаленная работа,1,"Информационные технологии, интернет, телеком"
2,25284500,84,Ставрополь,5402.0,full,Полная занятость,between3And6,От 3 до 6 лет,"JavaScript, HTML5, CSS3, AngularJS, Bootstrap",Frontend-разработчик,2018-05-04T09:24:18+0300,RUR,60000.0,80000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
3,25641559,1,Москва,1554.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"1С программирование, 1С: Бухгалтерия, 1С Управ...",Программист-консультант 1С,2018-05-06T10:49:05+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
4,25527035,2,Санкт-Петербург,3289100.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Менеджер по продажам,2018-05-05T16:15:16+0300,RUR,35000.0,100000.0,flexible,Гибкий график,1,"Информационные технологии, интернет, телеком"
5,25178591,1,Москва,2353123.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Системный аналитик,2018-05-07T00:54:39+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
6,25449125,1,Москва,934019.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Java-разработчик,2018-05-06T11:41:28+0300,RUR,120000.0,220000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
7,25459894,1,Москва,1053428.0,full,Полная занятость,between3And6,От 3 до 6 лет,"Linux, AWS, Proxmox, Vagrant, Docker, Админист...",Системный администратор (DevOps),2018-05-06T17:00:04+0300,RUR,100000.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
8,25041175,2,Санкт-Петербург,934019.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Java разработчик (middle/senior),2018-05-05T18:43:16+0300,RUR,120000.0,220000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
9,25295125,78,Самара,2618807.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Коммуникабельность, Аналитический склад ума, Н...",Менеджер по работе с корпоративными клиентами,2018-05-06T11:45:27+0300,RUR,35000.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
10,25446129,1,Москва,1300820.0,full,Полная занятость,between3And6,От 3 до 6 лет,"SCALA, Java, Spark, NoSQL, Big Data",Senior Java/Scala developer (BigData),2018-05-06T08:21:43+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
11,25632259,2,Санкт-Петербург,2470951.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"PHP, Yii2, PostgreSQL, ООП",PHP Developer / Разработчик PHP,2018-05-05T16:25:43+0300,RUR,110000.0,NaN,remote,Удаленная работа,1,"Информационные технологии, интернет, телеком"
12,25595230,1,Москва,2700524.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"1С программирование, 1С: Бухгалтерия, 1С: Пред...",Программист 1С,2018-05-06T09:30:12+0300,RUR,80000.0,100000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
13,25534356,72,Пермь,1931419.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"PHP, Atlassian Jira, Git, MySQL, Yii, Symfony,...",Backend-разработчик,2018-05-06T09:07:45+0300,RUR,30000.0,90000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
14,25416786,69,Орел,2253456.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Информационные технологии, Информационная безо...",Руководитель технического отдела / Team Lead,2018-05-05T23:55:10+0300,RUR,NaN,70000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
15,25337548,1,Москва,2942396.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Java EE, JavaScript, Java SE, SQL, jQuery, Jav...",Java-разработчик,2018-05-05T11:29:27+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
16,24665195,1,Москва,656166.0,full,Полная занятость,between3And6,От 3 до 6 лет,"JavaScript, REST, jQuery, CSS, HTML, Git, Рабо...",Ведущий разработчик Frontend / Frontend Develo...,2018-05-04T11:13:51+0300,RUR,160000.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
17,25341043,4,Новосибирск,913002.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Администрирование серверов Linux, Техническая ...",Администратор Linux (DevOps),2018-05-05T13:38:07+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
18,25469872,1,Москва,1747017.0,full,Полная занятость,between3And6,От 3 до 6 лет,"HTML, CSS, JavaScript, jQuery, Mercurial, Git,...",Frontend-Developer React,2018-05-04T10:36:17+0300,RUR,100000.0,170000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
19,25531733,2,Санкт-Петербург,1577832.0,full,Полная занятость,between3And6,От 3 до 6 лет,"QA, Регресионное тестирование, Linux, Scrum, A...",QA Lead / Ведущий специалист по тестированию,2018-05-06T01:08:25+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
20,25531764,2,Санкт-Петербург,1577832.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"CRM, zendesk, Консультирование клиентов, Техни...",Специалист поддержки клиентов,2018-05-06T02:18:02+0300,RUR,60000.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
21,25526867,1,Москва,2276869.0,full,Полная занятость,between3And6,От 3 до 6 лет,"C++, Lua, проектирование печатных плат",Инженер-электронщик микроконтроллеров,2018-05-05T16:11:18+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
22,25512336,26,Воронеж,748699.0,full,Полная занятость,noExperience,Нет опыта,NaN,Программист 1С (программист-стажер 1С),2018-05-05T09:53:09+0300,RUR,20000.0,30000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
23,25578876,1,Москва,5402.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Аналитик внедрения информационных систем,2018-05-05T11:43:40+0300,RUR,80000.0,100000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
24,25662140,2,Санкт-Петербург,745841.0,full,Полная занятость,noExperience,Нет опыта,"QA, Junior, Mobile development, Web developmen...",Junior QA,2018-05-04T09:58:44+0300,USD,800.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
25,25582544,1,Москва,934019.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Ведущий программист 1C,2018-05-05T13:33:42+0300,RUR,100000.0,190000.0,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
26,25528387,88,Казань,913233.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Тестировщик ПО,2018-05-05T16:57:45+0300,RUR,30000.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
27,23572477,2,Санкт-Петербург,1573351.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Java, Spring Framework",Java Developer,2018-05-04T17:26:45+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
28,25422324,2,Санкт-Петербург,1054705.0,full,Полная занятость,noExperience,Нет опыта,NaN,Консультант по внедрению и сопровождению 1С,2018-05-05T08:38:02+0300,NaN,NaN,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
29,25486171,2,Санкт-Петербург,588914.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,"Senior Backend Developer (Python, Golang)",2018-05-04T22:31:11+0300,RUR,110000.0,NaN,fullDay,Полный день,1,"Информационные технологии, интернет, телеком"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19807,25617656,1,Москва,816.0,full,Полная занятость,moreThan6,Более 6 лет,NaN,Специалист тендерного отдела (внутренние закупки),2018-05-04T13:05:12+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19808,25407542,1,Москва,816.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Product manager (Oracle),2018-04-23T11:11:03+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19809,25440649,1,Москва,1520642.0,full,Полная занятость,noExperience,Нет опыта,"внимательность, Грамотность",Специалист тендерного отдела,2018-04-17T18:58:33+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19810,25103683,23,Владимир,665467.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Ведущий специалист по обучению (услуги по обуч...,2018-04-23T15:29:18+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19811,24983215,53,Краснодар,2118134.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Специалист по закупкам,2018-05-03T08:47:33+0300,RUR,25000.0,30000.0,fullDay,Полный день,26,Закупки
19812,25534620,68,Омск,1006743.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Специалист по закупкам ( 44 ФЗ),2018-04-24T09:17:36+0300,RUR,20000.0,NaN,fullDay,Полный день,26,Закупки
19813,25523145,1374,Нефтеюганск,197135.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Ведущий специалист сектора развития и планиров...,2018-04-23T14:19:22+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19814,25437016,72,Пермь,1597934.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Закупки, Ведение переговоров, Управление прода...",Менеджер по снабжению,2018-04-17T15:45:34+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19815,25493475,92,Тула,1059553.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Специалист по закупкам,2018-04-20T11:58:52+0300,RUR,28000.0,NaN,fullDay,Полный день,26,Закупки
19816,25369879,1,Москва,2828754.0,full,Полная занятость,noExperience,Нет опыта,"MS Excel, MS Word, 1С: Бухгалтерия, CRM",Менеджер по закупкам и работе с партнерами,2018-05-06T17:50:39+0300,RUR,40000.0,65000.0,fullDay,Полный день,26,Закупки
19817,25044639,1,Москва,3177.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Менеджер по закупкам,2018-04-19T13:44:24+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19818,25365987,1,Москва,725989.0,full,Полная занятость,between3And6,От 3 до 6 лет,"Английский язык, SAP, Логистика",Специалист по логистике и закупкам,2018-04-16T13:32:38+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19819,25300707,1,Москва,2629400.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"ВЭД, Закупки, Логистика поставок, Ведение пере...",Менеджер по закупкам,2018-05-06T14:30:16+0300,RUR,80000.0,100000.0,fullDay,Полный день,26,Закупки
19820,25373606,1,Москва,7040.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Менеджер по закупкам,2018-05-04T08:51:07+0300,RUR,60000.0,NaN,fullDay,Полный день,26,Закупки
19821,25253240,1,Москва,816.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Ассистент отдела закупок/Ассистент менеджера п...,2018-05-04T13:07:42+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19822,25285315,1,Москва,816.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Специалист по закупкам ( IT-оборудование),2018-05-04T13:07:28+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19823,25387839,1,Москва,4526.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Ведущий менеджер по продуктам и закупкам,2018-04-25T14:52:29+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19824,25488505,112,Ярославль,67611.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Менеджер по сопровождению торгов,2018-04-20T08:58:00+0300,RUR,28000.0,35000.0,fullDay,Полный день,26,Закупки
19825,25257683,1204,Бердск,2622312.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Менеджер по снабжению,2018-05-02T19:17:02+0300,RUR,30000.0,40000.0,fullDay,Полный день,26,Закупки
19826,25503951,1,Москва,597423.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Менеджер по закупкам/Purchase manager,2018-05-06T09:44:00+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19827,25326612,1,Москва,2592107.0,full,Полная занятость,between3And6,От 3 до 6 лет,"Category Management, Категорийный менеджмент, ...",Category manager,2018-05-04T16:50:22+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19828,25602266,84,Ставрополь,876275.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Специалист отдела закупок / по выбору поставщиков,2018-05-06T09:03:04+0300,RUR,20000.0,25000.0,fullDay,Полный день,26,Закупки
19829,25603653,112,Ярославль,971924.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Менеджер по снабжению и закупкам,2018-05-03T08:14:04+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19830,25493705,1,Москва,12504.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Менеджер по закупкам,2018-05-05T12:07:20+0300,NaN,NaN,NaN,fullDay,Полный день,26,Закупки
19831,25530892,61,Йошкар-Ола,2225569.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Няня,2018-04-23T19:30:15+0300,RUR,15000.0,NaN,flexible,Гибкий график,27,Домашний персонал
19832,25292524,49,Киров,1671906.0,part,Частичная занятость,between1And3,От 1 года до 3 лет,NaN,Домработница/домработник,2018-04-09T10:32:52+0300,NaN,NaN,NaN,flexible,Гибкий график,27,Домашний персонал
19833,25684255,81,Южно-Сахалинск,19602.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Монтаж оборудования, Монтаж инженерных систем,...",Монтажник оборудования связи,2018-05-07T03:22:41+0300,RUR,NaN,50000.0,fullDay,Полный день,29,Рабочий персонал
19834,25684252,102,Хабаровск,19602.0,full,Полная занятость,between1And3,От 1 года до 3 лет,"Монтаж оборудования, Производство строительно-...",Монтажник оборудования связи,2018-05-07T03:19:22+0300,NaN,NaN,NaN,fullDay,Полный день,29,Рабочий персонал
19835,25608185,2,Санкт-Петербург,84585.0,full,Полная занятость,between1And3,От 1 года до 3 лет,NaN,Грузчик-техник,2018-04-27T18:43:02+0300,RUR,45000.0,NaN,fullDay,Полный день,29,Рабочий персонал
19836,25086936,24,Волгоград,967438.0,full,Полная занятость,between3And6,От 3 до 6 лет,NaN,Приборист (6 разряд),2018-04-25T09:07:10+0300,NaN,NaN,NaN,fullDay,Полный день,29,Рабочий персонал

In [29]:
df_vacancy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19837 entries, 0 to 19836
Data columns (total 18 columns):
id                     19837 non-null int64
area_id                19837 non-null int64
area_name              19837 non-null object
employer_id            19813 non-null float64
employment_id          19805 non-null object
employment_name        19805 non-null object
experience_id          19805 non-null object
experience_name        19805 non-null object
key_skills             6654 non-null object
name                   19837 non-null object
published_at           19837 non-null object
salary_currency        10358 non-null object
salary_from            9611 non-null float64
salary_to              4594 non-null float64
schedule_id            19805 non-null object
schedule_name          19805 non-null object
specialization_id      19837 non-null int64
specialization_name    19837 non-null object
dtypes: float64(3), int64(3), object(12)
memory usage: 2.7+ MB

In [30]:
# Разделение на обучающую и тестовую выборку по id, который соответствует порядку добавления вакаансий на сайт.
count_df = len(df_vacancy)
df_vacancy.sort_values(by='id', ascending=True, inplace=True)
df_vacancy_test = df_vacancy[int(2*count_df/3):]
df_vacancy_train = df_vacancy[:int(2*count_df/3)]

In [31]:
# Первичный анализ данных и формирование признаков рекомендуется проводить на обучающей выборке.
df_vacancy_train.describe()

,id,area_id,employer_id,salary_from,salary_to,specialization_id
count,1.322400e+04,13224.000000,1.321900e+04,6555.000000,2695.000000,13224.000000
mean,2.427900e+07,339.665910,6.285927e+05,52182.384592,85212.069388,3.595886
std,1.580547e+06,800.582578,8.361471e+05,35127.270832,59299.426350,4.907250
min,7.160726e+06,1.000000,1.900000e+01,25.000000,30.000000,1.000000
25%,2.405097e+07,1.000000,4.114400e+04,30000.000000,40000.000000,1.000000
50%,2.489626e+07,17.000000,8.458500e+04,43000.000000,70000.000000,1.000000
75%,2.524230e+07,88.000000,9.994420e+05,64000.000000,120000.000000,4.000000
max,2.540689e+07,5962.000000,3.353801e+06,300000.000000,1000000.000000,29.000000

In [32]:
# Удаление записей с пропущенными значениями NaN.
df_vacancy_train = df_vacancy_train[np.isfinite(df_vacancy_train['salary_from']) &
                                    np.isfinite(df_vacancy_train['area_id']) &
                                    np.isfinite(df_vacancy_train['employer_id']) &
                                    np.isfinite(df_vacancy_train['specialization_id'])]

In [33]:
df_company = pd.read_csv('hh_company.csv')
df_company.head()

,employer_id,employer_name,employer_site,industry_id,industry_name
0,1747017.0,Колтач Солюшнс,NaN,7,"Информационные технологии, системная интеграци..."
1,553714.0,Нотамедиа,NaN,7,"Информационные технологии, системная интеграци..."
2,5402.0,НЕОЛАНТ,NaN,7,"Информационные технологии, системная интеграци..."
3,1554.0,Infosuite,NaN,7,"Информационные технологии, системная интеграци..."
4,3289100.0,Медиа Бокс,NaN,7,"Информационные технологии, системная интеграци..."

In [34]:
df_vacancy_train = pd.merge(df_vacancy_train, df_company, on='employer_id')
df_vacancy_train.head()

,id,area_id,area_name,employer_id,employment_id,employment_name,experience_id,experience_name,key_skills,name,...,salary_from,salary_to,schedule_id,schedule_name,specialization_id,specialization_name,employer_name,employer_site,industry_id,industry_name
0,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,35000.0,NaN,flexible,Гибкий график,3,"Маркетинг, реклама, PR",Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци..."
1,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,35000.0,NaN,flexible,Гибкий график,3,"Маркетинг, реклама, PR",Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци..."
2,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,35000.0,NaN,flexible,Гибкий график,3,"Маркетинг, реклама, PR",Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци..."
3,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,35000.0,NaN,flexible,Гибкий график,3,"Маркетинг, реклама, PR",Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци..."
4,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,35000.0,NaN,flexible,Гибкий график,3,"Маркетинг, реклама, PR",Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци..."

In [35]:
df_cities = pd.read_csv('cities.csv')
df_cities.head()

,Индекс,Тип региона,Регион,Тип района,Район,Тип города,Город,Тип н/п,Н/п,Код КЛАДР,...,Уровень по ФИАС,Признак центра района или региона,Код ОКАТО,Код ОКТМО,Код ИФНС,Часовой пояс,Широта,Долгота,Федеральный округ,Население
0,385200.0,Респ,Адыгея,NaN,NaN,г,Адыгейск,NaN,NaN,100000200000,...,4: город,0,79403000000,7.970300e+10,107,UTC+3,44.878372,39.190172,Южный,12689
1,385000.0,Респ,Адыгея,NaN,NaN,г,Майкоп,NaN,NaN,100000100000,...,4: город,2,79401000000,7.970100e+10,105,UTC+3,44.609827,40.100653,Южный,144055
2,649000.0,Респ,Алтай,NaN,NaN,г,Горно-Алтайск,NaN,NaN,400000100000,...,4: город,2,84401000000,8.470100e+07,400,UTC+7,51.958268,85.960296,Сибирский,62861
3,658125.0,край,Алтайский,NaN,NaN,г,Алейск,NaN,NaN,2200000200000,...,4: город,0,1403000000,1.703000e+06,2201,UTC+7,52.492091,82.779415,Сибирский,28528
4,656000.0,край,Алтайский,NaN,NaN,г,Барнаул,NaN,NaN,2200000100000,...,4: город,2,1401000000,1.701000e+06,2200,UTC+7,53.348115,83.779836,Сибирский,635585

In [36]:
df_cities = df_cities[['Город','Широта','Долгота','Население', 'Регион']]
df_cities['Город'] = df_cities.apply(lambda row: row['Регион']
                                     if type(row['Город']) != str and np.isnan(row['Город'])
                                     else row['Город'], axis=1)
df_cities = df_cities[['Город','Широта','Долгота','Население']]
df_cities = df_cities.rename(index=str, columns={"Город": "area_name"})
df_cities = df_cities.rename(index=str, columns={"Широта": "latitude"})
df_cities = df_cities.rename(index=str, columns={"Долгота": "longitude"})
df_cities = df_cities.rename(index=str, columns={"Население": "population"})

In [37]:
moscow_latitude, moscow_longitude = list(df_cities.loc[df_cities.area_name == 'Москва'][['latitude','longitude']].iloc[0])
moscow_latitude, moscow_longitude

(55.7538789, 37.6203735)

In [38]:
df_cities['distance_to_Moscow'] = df_cities.apply(lambda row: vincenty((moscow_latitude, moscow_longitude),
                                                                       (row.latitude, row.longitude)).kilometers, axis=1)
df_cities.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning:

Vincenty is deprecated and is going to be removed in geopy 2.0. Use `geopy.distance.geodesic` (or the default `geopy.distance.distance`) instead, which is more accurate and always converges.

       area_name   latitude  longitude population  distance_to_Moscow
0       Адыгейск  44.878372  39.190172      12689         1214.804843
1         Майкоп  44.609827  40.100653     144055         1251.957644
2  Горно-Алтайск  51.958268  85.960296      62861         3142.838553
3         Алейск  52.492091  82.779415      28528         2921.575344
4        Барнаул  53.348115  83.779836     635585         2943.040433

In [39]:
df_vacancy_train = pd.merge(df_vacancy_train, df_cities, on='area_name')
df_vacancy_train.head()

,id,area_id,area_name,employer_id,employment_id,employment_name,experience_id,experience_name,key_skills,name,...,specialization_id,specialization_name,employer_name,employer_site,industry_id,industry_name,latitude,longitude,population,distance_to_Moscow
0,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,3,"Маркетинг, реклама, PR",Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци...",59.939125,30.315822,4848742,636.038853
1,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,3,"Маркетинг, реклама, PR",Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци...",59.939125,30.315822,4848742,636.038853
2,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,3,"Маркетинг, реклама, PR",Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци...",59.939125,30.315822,4848742,636.038853
3,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,3,"Маркетинг, реклама, PR",Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци...",59.939125,30.315822,4848742,636.038853
4,7160726,2,Санкт-Петербург,558625.0,part,Частичная занятость,noExperience,Нет опыта,NaN,Оператор call-центра,...,3,"Маркетинг, реклама, PR",Cистема Северо-Запад,NaN,7,"Информационные технологии, системная интеграци...",59.939125,30.315822,4848742,636.038853

In [40]:
for column in df_vacancy_train.columns:
    print(column)
    values = df_vacancy_train[column].dropna().unique()
    sorted_values = sorted(values.tolist())
    print(len(sorted_values))
    if len(sorted_values) < 20:
        print(f"{sorted_values}")
    else:
        print(f"[{min(sorted_values)}: {max(sorted_values)}]")
    inter = set(df_vacancy_train[column].unique()) - set(df_vacancy_train[column].dropna().unique())
    if inter:
        print(inter)
    print()

id
6151
[7160726: 25406869]

area_id
337
[1: 4455]

area_name
337
[Абакан: Яхрома]

employer_id
1349
[139.0: 3351855.0]

employment_id
4
['full', 'part', 'probation', 'project']

employment_name
4
['Полная занятость', 'Проектная работа', 'Стажировка', 'Частичная занятость']

experience_id
4
['between1And3', 'between3And6', 'moreThan6', 'noExperience']

experience_name
4
['Более 6 лет', 'Нет опыта', 'От 1 года до 3 лет', 'От 3 до 6 лет']

key_skills
1626
[.NET Framework, ASP.NET, C#, Entity Framework, MVC, LINQ, JavaScript, HTML5, CSS3, MS SQL Server, Angular, WebAPI: № ФЗ-223, №ФЗ-44, B2B Продажи, Ведение переговоров, Заключение договоров, Поиск и привлечение клиентов]
{nan}

name
2590
[.NEТ/C# Developer: Юрист по международному праву]

published_at
4077
[2018-04-07T10:01:09+0300: 2018-05-07T05:51:25+0300]

salary_currency
4
['EUR', 'RUR', 'UAH', 'USD']

salary_from
178
[25.0: 300000.0]

salary_to
129
[30.0: 1000000.0]
{nan}

schedule_id
5
['flexible', 'flyInFlyOut', 'fullDay', 'remote', 'shift']

schedule_name
5
['Вахтовый метод', 'Гибкий график', 'Полный день', 'Сменный график', 'Удаленная работа']

specialization_id
26
[1: 26]

specialization_name
26
[Автомобильный бизнес: Юристы]

employer_name
1341
[1 Мегамир: группа компаний Стэк]

employer_site
0
[]
{nan}

industry_id
1
[7]

industry_name
1
['Информационные технологии, системная интеграция, интернет']

latitude
340
[42.8240404: 69.07650290000001]

longitude
340
[20.5072458: 158.6559142]

population
340
[1000679: 99762]

distance_to_Moscow
340
[0.0: 6796.346928845302]

In [41]:
categorial_factors = ['area_name',
                      'employment_name',
                      'salary_currency',
                      'schedule_name',
                      'specialization_id'
                  ]
quality_factors = ['latitude',
                   'longitude',
                   'population',
                   'distance_to_Moscow'
                  ]

In [42]:
df_vacancy_train.describe()

,id,area_id,employer_id,salary_from,salary_to,specialization_id,employer_site,industry_id,latitude,longitude,distance_to_Moscow
count,4.495943e+06,4.495943e+06,4.495943e+06,4.495943e+06,393001.000000,4.495943e+06,0.0,4495943.0,4.495943e+06,4.495943e+06,4.495943e+06
mean,2.407015e+07,1.229713e+03,1.092549e+05,4.999383e+04,124056.618418,5.353185e+00,NaN,7.0,5.499234e+01,4.324840e+01,5.374303e+02
std,1.677781e+06,9.493956e+02,2.237704e+05,2.081256e+04,45219.070170,3.701526e+00,NaN,0.0,3.206124e+00,1.479496e+01,9.083851e+02
min,7.160726e+06,1.000000e+00,1.390000e+02,2.500000e+01,30.000000,1.000000e+00,NaN,7.0,4.282404e+01,2.050725e+01,0.000000e+00
25%,2.320238e+07,7.200000e+01,7.863800e+04,4.000000e+04,90000.000000,4.000000e+00,NaN,7.0,5.483252e+01,3.748310e+01,5.462097e+01
50%,2.492785e+07,1.793000e+03,7.863800e+04,5.000000e+04,150000.000000,5.000000e+00,NaN,7.0,5.571703e+01,3.821940e+01,1.251301e+02
75%,2.509473e+07,2.054000e+03,7.863800e+04,6.200000e+04,150000.000000,5.000000e+00,NaN,7.0,5.612816e+01,4.131696e+01,7.054913e+02
max,2.540687e+07,4.455000e+03,3.351855e+06,3.000000e+05,1000000.000000,2.600000e+01,NaN,7.0,6.907650e+01,1.586559e+02,6.796347e+03

In [44]:
df_vacancy_train.columns

Index(['id', 'area_id', 'area_name', 'employer_id', 'employment_id',
       'employment_name', 'experience_id', 'experience_name', 'key_skills',
       'name', 'published_at', 'salary_currency', 'salary_from', 'salary_to',
       'schedule_id', 'schedule_name', 'specialization_id',
       'specialization_name', 'employer_name', 'employer_site', 'industry_id',
       'industry_name', 'latitude', 'longitude', 'population',
       'distance_to_Moscow'],
      dtype='object')

In [ ]:
#Приводим к одной валюте
def valute(salary, currency):
    if currency == 'USD':
        return salary*65
    elif currency == 'EUR':
        return salary*74
    return salary

print(df_vacancy_train['salary_currency'].unique())
df_vacancy_train['salary_from'] = df_vacancy_train.apply(lambda row: valute(row.salary_from, row.salary_currency), axis=1)

['RUR' 'EUR' 'USD' 'UAH']

In [ ]:
areas = df_vacancy_train[['id', 'area_name']].\
        groupby(['area_name']).\
        agg({'id': 'count'}).\
        rename(columns={'id': 'area_vacancy_count'})
areas.head()

In [ ]:
areas = df_vacancy_train[['salary_from', 'area_name']].\
        groupby(['area_name']).\
        agg({'salary_from': 'mean'}).\
        rename(columns={'salary_from': 'area_salary_mean'})
areas.head()

### Графический анализ

In [17]:
vis_data = df_vacancy_train[quality_factors + ['salary_from']].sample(frac=0.001)
sns.pairplot(vis_data, hue='salary_from')

ValueError: setting an array element with a sequence

AttributeError: 'NoneType' object has no attribute 'seq'

In [ ]:
for factor in categorial_factors:
    print(factor)
    g = sns.factorplot(factor,'salary_from',data=df_vacancy_train.sample(frac=0.001), aspect=2.5)
    g.set_xticklabels(rotation=0)
    plt.show()

### Формирование признаков

In [9]:
train_y = df_vacancy_train['salary_from']
train_X = df_vacancy_train[['area_id', 'employer_id', 'specialization_id']]

## Обучение модели

In [10]:
reg = linear_model.LinearRegression()
reg.fit(train_X, train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
# Коэф. уравнения.
reg.coef_

array([-2.44679546e+00, -3.34828989e-03, -1.54451998e+03])

## Оценка качества обучения

In [12]:
# Точность на обучающей выборке.
train_r2 = r2_score(train_y, reg.predict(train_X))
train_r2

0.06585492603413479

In [13]:
# Подготовка тестовой выборки.
df_vacancy_test = df_vacancy_test[np.isfinite(df_vacancy_test['salary_from']) &
                                  np.isfinite(df_vacancy_test['area_id']) &
                                  np.isfinite(df_vacancy_test['employer_id']) &
                                  np.isfinite(df_vacancy_test['specialization_id'])]
test_y = df_vacancy_test['salary_from']
test_X = df_vacancy_test[['area_id', 'employer_id', 'specialization_id']]
# Точность на тестовой выборке.
test_r2 = r2_score(test_y, reg.predict(test_X))
test_r2

0.021286993703545587

In [17]:
def adjusted_r2_score(test_y, test_X, predict_y):
    '''Коэффициент детерминации, скорректированный на число признаков.'''
    n=test_X.shape[0]       # количество наблюдений
    p=test_X.shape[1] - 1   # количество признаков, включенных в модель
    r2 = r2_score(test_y, predict_y)
    adj_r2 = 1 - (1 - r2) * ((n - 1)/(n-p-1))
    return adj_r2

# Скорректированная точность на тестовой выборке.
test_adj_r2 = adjusted_r2_score(test_y, test_X, reg.predict(test_X))
test_adj_r2

0.02064289169216249

Качество модели очень плохое, поскольку признаков мало и использован простейший способ кодирования категорильнаых признаков, который не подходит для линейны модели. Необходимиый результат коэф. детерминации 0.7